// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        516,
				FirstName: "soluta",
				LastName:  "molestias",
				Email:     "consectetur_quis@Quimm.info",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        338,
				FirstName: "a",
				LastName:  "voluptate",
				Email:     "HelenHarrison@Oozz.edu",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        903,
				FirstName: "eos",
				LastName:  "aut",
				Email:     "AntonioMartin@Ailane.info",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        50,
				FirstName: "nulla",
				LastName:  "ipsam",
				Email:     "cCruz@Tavu.edu",
				Visible:   true,
			},
		}
	return res, nil
}
