// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUser) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        175,
				FirstName: "ipsam",
				LastName:  "et",
				Email:     "maiores_quasi@Vitz.gov",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        19,
				FirstName: "blanditiis",
				LastName:  "nihil",
				Email:     "vel_eos_aut@Skidoo.mil",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        300,
				FirstName: "suscipit",
				LastName:  "nihil",
				Email:     "tempora@Dabjam.net",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        329,
				FirstName: "voluptatibus",
				LastName:  "quae",
				Email:     "JuanMorgan@Edgewire.gov",
				Visible:   true,
			},
		}
	return res, nil
}
