// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        42,
				FirstName: "est",
				LastName:  "perferendis",
				Email:     "dolorum@BlogXS.name",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        554,
				FirstName: "asperiores",
				LastName:  "est",
				Email:     "iGonzales@Chatterbridge.biz",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        25,
				FirstName: "distinctio",
				LastName:  "nihil",
				Email:     "EarlGriffin@Babbleblab.net",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        704,
				FirstName: "veritatis",
				LastName:  "eum",
				Email:     "NicholasKnight@Brainsphere.info",
				Visible:   true,
			},
		}
	return res, nil
}
